### PR TITLE
add Member's Link 

### PR DESCRIPTION
**Pull request by iganari**
## purpose

- Add Suwa's Twitter Link

## What you did

- Add Link

### CODE REVIEW

**Comment by iganari** [comment]
Plz Check !! ;)

**Comment by Robjam** [comment]
Is this PR for all members or just the ones to change? If this is for all members, we should set a deadline and merge then. If only these changes are okay, we should merge this now. I'll approve in advance.

**Review by Robjam — APPROVED** [review]
Approved, but with a question about this PR's lifetime.

**Comment by iganari** [comment]
@Robjam 
I'm really sorry for my late confirmation... :(

> Is this PR for all members or just the ones to change?

Not All member, But Just ones(Two members)

Therefore, I think I can change it right away.

Are you okay?

**Pull request merged**
